//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Borrows = new HashSet<Borrow>();
        }
    
        public int BookID { get; set; }
        public string Book_Name { get; set; }
        public string Genre { get; set; }
        public string Image { get; set; }
        public int Quantity { get; set; }
        public string Cover_Type { get; set; }
        public string Book_Type { get; set; }
        public int AdminID { get; set; }
        public string Book_Description { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrow> Borrows { get; set; }
    }
}
